### ISSUE TITLE
unable to load data from SwissMeteo

### ISSUE THREAD

**Issue by aracloud** [baerengraben/iobroker.swiss-weather-api#13]
Hi

I installed the latest version 0.2.0 and I get following errors:

```
2020-07-05 22:30:03.261 - info: swiss-weather-api.0 (15985) starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.swiss-weather-api, node: v12.18.1, js-controller: 3.1.6
2020-07-05 22:30:03.321 - info: swiss-weather-api.0 (15985) Swiss-Weather-API: Start getWeatherInfos
2020-07-05 22:30:03.613 - error: swiss-weather-api.0 (15985) uncaught exception: Cannot convert undefined or null to object
2020-07-05 22:30:03.617 - error: swiss-weather-api.0 (15985) TypeError: Cannot convert undefined or null to object
at Function.keys ()
at IncomingMessage. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1402:18)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1221:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-07-05 22:30:03.641 - error: swiss-weather-api.0 (15985) uncaught exception: Cannot read property 'ttn' of undefined
2020-07-05 22:30:03.643 - error: swiss-weather-api.0 (15985) TypeError: Cannot read property 'ttn' of undefined
at IncomingMessage. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:602:26)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1221:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-07-05 22:30:03.671 - error: swiss-weather-api.0 (15985) uncaught exception: Cannot read property 'smb3' of undefined
2020-07-05 22:30:03.673 - error: swiss-weather-api.0 (15985) TypeError: Cannot read property 'smb3' of undefined
at IncomingMessage. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1690:26)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1221:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-07-05 22:30:03.692 - error: swiss-weather-api.0 (15985) uncaught exception: Cannot read property 'ttn' of undefined
2020-07-05 22:30:03.694 - error: swiss-weather-api.0 (15985) TypeError: Cannot read property 'ttn' of undefined
at IncomingMessage. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:191:26)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1221:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-07-05 22:30:03.713 - error: swiss-weather-api.0 (15985) uncaught exception: Cannot read property 'toString' of undefined
2020-07-05 22:30:03.724 - error: swiss-weather-api.0 (15985) TypeError: Cannot read property 'toString' of undefined
at /opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1394:34
at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3216:55
at /opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-05 22:30:03.726 - error: swiss-weather-api.0 (15985) uncaught exception: Cannot read property '0' of undefined
2020-07-05 22:30:03.728 - error: swiss-weather-api.0 (15985) TypeError: Cannot read property '0' of undefined
at /opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:595:28
at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3216:55
at /opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-05 22:30:03.736 - error: swiss-weather-api.0 (15985) uncaught exception: Cannot read property 'toString' of undefined
2020-07-05 22:30:03.738 - error: swiss-weather-api.0 (15985) TypeError: Cannot read property 'toString' of undefined
at /opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1664:34
at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3216:55
at /opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-05 22:30:03.751 - info: swiss-weather-api.0 (15985) terminating
2020-07-05 22:30:03.755 - info: swiss-weather-api.0 (15985) Terminated (NO_ERROR): Without reason
2020-07-05 22:30:03.778 - error: swiss-weather-api.0 (15985) uncaught exception: Cannot read property '0' of undefined
2020-07-05 22:30:03.780 - error: swiss-weather-api.0 (15985) TypeError: Cannot read property '0' of undefined
at /opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1682:34
at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3216:55
at /opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-05 22:30:03.786 - error: swiss-weather-api.0 (15985) uncaught exception: Cannot read property 'toString' of undefined
2020-07-05 22:30:03.791 - error: swiss-weather-api.0 (15985) TypeError: Cannot read property 'toString' of undefined
at /opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:165:34
at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3216:55
at /opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-05 22:30:03.792 - error: swiss-weather-api.0 (15985) uncaught exception: Cannot read property 'date' of undefined
2020-07-05 22:30:03.794 - error: swiss-weather-api.0 (15985) TypeError: Cannot read property 'date' of undefined
at /opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:183:31
at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3216:55
at /opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-05 22:30:04.282 - info: host.iobroker instance system.adapter.swiss-weather-api.0 terminated with code 0 (NO_ERROR)


```

What is the issue here? 

I followed the install guide and I hit the latitude and longitude from my canton I live in central Switzerland with the corresponding key and secret of myApp.

Thank you for your help!
ara

**Comment by baerengraben** [comment]
Hi @aracloud 
Can you please activate loglevel "debug" and provide the log?
Regards
Ralph

**Comment by baerengraben** [comment]
Hi
Since the creation of the adapter, SRF seems to have added new products. At the beginning, to my knowledge, only SRG-SSR-PUBLIC-API-V2 was available. Thanks for this hint and PR are always very welcome :)
Many greetings
