### ISSUE TITLE
Adapter restarts when an attribute is not deliverd by SRG

### ISSUE THREAD

**Issue by baerengraben** [baerengraben/ioBroker.swiss-weather-api#23]
It happens, that SRG-API doesn't deliver all Attributes. Here for example the attribute rr3 is no delivered for 24hour forecast, hour1 (AM 01:00):

```

2021-01-12 14:09:18.694  - [31merror[39m: swiss-weather-api.0 (29813) uncaught exception: Cannot read property 'rr3' of undefined
2021-01-12 14:09:18.696  - [31merror[39m: swiss-weather-api.0 (29813) TypeError: Cannot read property 'rr3' of undefined
    at /opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:2088:47
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3216:55
    at /opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703
    at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
    at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The Adapter should deal with this. Actualy it crashes, and restarts again. After restarting, it get's all weather-data and crashes again. And so on...

The Adapter shoud check if the attribute is deliverd. if not => skip the attribute.

this is, what SRG delivers for this particular example. Attributes pr3 and rr3 are missing:

`{
  "formatted_date": "12.01.2021",
  "date": "2021-01-12",
  "24hours": [
    {
      "date": "2021-01-12T01:00:00+0100",
      "values": [
        {
          "smb3": "-10"
        },
        {
          "ttt": "-5.1"
        },
        {
          "fff": "4"
        },
        {
          "ffx3": ""
        },
        {
          "ddd": "208"
        }
      ]
    },
    {
...
`

**Comment by baerengraben** [comment]
resolved with 0.9.0
