### ISSUE TITLE
Adapter chrashes when srf is not sending valid json

### ISSUE THREAD

**Issue by baerengraben** [baerengraben/ioBroker.swiss-weather-api#48]
Adapter crashes when srf is not sending a valid json. after trying to restart, adapter will stay stopped.

Use 

`typeof body[0].id == undefined `

to check if variable is there. NOT

`body[0].id === undefined `

> 
> 2021-06-09 18:49:25.158  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property '60minutes' of undefined
> --
> 2021-06-09 18:49:25.164  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property '60minutes' of undefined
> at IncomingMessage. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1480:17)
> at IncomingMessage.emit (events.js:327:22)
> at endReadableNT (_stream_readable.js:1221:12)
> at processTicksAndRejections (internal/process/task_queues.js:84:21)
> 2021-06-09 18:49:25.166  - error: swiss-weather-api.0 (19183) Cannot read property '60minutes' of undefined
> 2021-06-09 18:49:25.222  - info: swiss-weather-api.0 (19183) cleaned everything up...
> 2021-06-09 18:49:25.225  - info: swiss-weather-api.0 (19183) terminating
> 2021-06-09 18:49:25.229  - warn: swiss-weather-api.0 (19183) Terminated (UNCAUGHT_EXCEPTION): Without reason
> 2021-06-09 18:49:25.232  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'id' of undefined
> 2021-06-09 18:49:25.235  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'id' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1128:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.237  - error: swiss-weather-api.0 (19183) Cannot read property 'id' of undefined
> 2021-06-09 18:49:25.241  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'lat' of undefined
> 2021-06-09 18:49:25.243  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'lat' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1143:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.245  - error: swiss-weather-api.0 (19183) Cannot read property 'lat' of undefined
> 2021-06-09 18:49:25.250  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'lon' of undefined
> 2021-06-09 18:49:25.253  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'lon' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1158:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.255  - error: swiss-weather-api.0 (19183) Cannot read property 'lon' of undefined
> 2021-06-09 18:49:25.259  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'station_id' of undefined
> 2021-06-09 18:49:25.260  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'station_id' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1173:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.262  - error: swiss-weather-api.0 (19183) Cannot read property 'station_id' of undefined
> 2021-06-09 18:49:25.265  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'timezone' of undefined
> 2021-06-09 18:49:25.266  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'timezone' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1188:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.267  - error: swiss-weather-api.0 (19183) Cannot read property 'timezone' of undefined
> 2021-06-09 18:49:25.270  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'default_name' of undefined
> 2021-06-09 18:49:25.271  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'default_name' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1203:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.273  - error: swiss-weather-api.0 (19183) Cannot read property 'default_name' of undefined
> 2021-06-09 18:49:25.275  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'alarm_region_id' of undefined
> 2021-06-09 18:49:25.277  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'alarm_region_id' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1218:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.278  - error: swiss-weather-api.0 (19183) Cannot read property 'alarm_region_id' of undefined
> 2021-06-09 18:49:25.281  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'alarm_region_name' of undefined
> 2021-06-09 18:49:25.282  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'alarm_region_name' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1233:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.284  - error: swiss-weather-api.0 (19183) Cannot read property 'alarm_region_name' of undefined
> 2021-06-09 18:49:25.286  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'district' of undefined
> 2021-06-09 18:49:25.288  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'district' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1248:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.289  - error: swiss-weather-api.0 (19183) Cannot read property 'district' of undefined
> 2021-06-09 18:49:25.292  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.293  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'geolocation_names' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1264:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.295  - error: swiss-weather-api.0 (19183) Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.297  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.298  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'geolocation_names' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1278:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.300  - error: swiss-weather-api.0 (19183) Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.306  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.307  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'geolocation_names' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1292:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.308  - error: swiss-weather-api.0 (19183) Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.310  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.312  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'geolocation_names' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1306:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.313  - error: swiss-weather-api.0 (19183) Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.315  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.317  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'geolocation_names' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1320:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.318  - error: swiss-weather-api.0 (19183) Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.320  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.321  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'geolocation_names' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1334:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.322  - error: swiss-weather-api.0 (19183) Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.324  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.326  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'geolocation_names' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1348:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.327  - error: swiss-weather-api.0 (19183) Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.329  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.330  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'geolocation_names' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1362:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.331  - error: swiss-weather-api.0 (19183) Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.334  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.335  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'geolocation_names' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1376:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.336  - error: swiss-weather-api.0 (19183) Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.357  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.358  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'geolocation_names' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1390:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.359  - error: swiss-weather-api.0 (19183) Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.361  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.362  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'geolocation_names' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1404:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.363  - error: swiss-weather-api.0 (19183) Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.366  - error: swiss-weather-api.0 (19183) uncaught exception: Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.367  - error: swiss-weather-api.0 (19183) TypeError: Cannot read property 'geolocation_names' of undefined
> at Immediate. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1418:28)
> at processImmediate (internal/timers.js:458:21)
> 2021-06-09 18:49:25.368  - error: swiss-weather-api.0 (19183) Cannot read property 'geolocation_names' of undefined
> 2021-06-09 18:49:25.917  - error: host.ioBroker-RasPi instance system.adapter.swiss-weather-api.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
> 2021-06-09 18:49:25.927  - info: host.ioBroker-RasPi Restart adapter system.adapter.swiss-weather-api.0 because enabled
> 2021-06-09 18:49:56.031  - info: host.ioBroker-RasPi instance system.adapter.swiss-weather-api.0 started with pid 14327
> 2021-06-09 18:49:58.704  - info:  swiss-weather-api.0 (14327) starting. Version 0.9.5 in  /opt/iobroker/node_modules/iobroker.swiss-weather-api, node: v12.18.2,  js-controller: 3.2.16
> 2021-06-09 18:49:58.764  - info: swiss-weather-api.0 (14327) longitude/longitude not set, get data from system
> 2021-06-09 18:49:58.807  - info: swiss-weather-api.0 (14327) system  longitude: 7.375587970018386 latitude: 47.04616448019215
> 2021-06-09 18:51:04.325  - error: swiss-weather-api.0 (14327) uncaught exception: Cannot read property 'id' of undefined
> 2021-06-09 18:51:04.329  - error: swiss-weather-api.0 (14327) TypeError: Cannot read property 'id' of undefined
> at IncomingMessage. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:2705:16)
> at IncomingMessage.emit (events.js:327:22)
> at endReadableNT (_stream_readable.js:1221:12)
> at processTicksAndRejections (internal/process/task_queues.js:84:21)
> 2021-06-09 18:51:04.330  - error: swiss-weather-api.0 (14327) Cannot read property 'id' of undefined
> 2021-06-09 18:51:04.348  - info: swiss-weather-api.0 (14327) cleaned everything up...
> 2021-06-09 18:51:04.350  - info: swiss-weather-api.0 (14327) terminating
> 2021-06-09 18:51:04.352  - warn: swiss-weather-api.0 (14327) Terminated (UNCAUGHT_EXCEPTION): Without reason
> 2021-06-09 18:51:05.072  - error: host.ioBroker-RasPi instance system.adapter.swiss-weather-api.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
> 2021-06-09 18:51:05.075  - info: host.ioBroker-RasPi Restart adapter system.adapter.swiss-weather-api.0 because enabled
> 2021-06-09 18:51:35.129  - info: host.ioBroker-RasPi instance system.adapter.swiss-weather-api.0 started with pid 15999
> 2021-06-09 18:51:37.933  - info:  swiss-weather-api.0 (15999) starting. Version 0.9.5 in  /opt/iobroker/node_modules/iobroker.swiss-weather-api, node: v12.18.2,  js-controller: 3.2.16
> 2021-06-09 18:51:37.992  - info: swiss-weather-api.0 (15999) longitude/longitude not set, get data from system
> 2021-06-09 18:51:38.026  - info: swiss-weather-api.0 (15999) system  longitude: 7.375587970018386 latitude: 47.04616448019215
> 2021-06-09 18:52:43.790  - error: swiss-weather-api.0 (15999) uncaught exception: Cannot read property 'id' of undefined
> 2021-06-09 18:52:43.794  - error: swiss-weather-api.0 (15999) TypeError: Cannot read property 'id' of undefined
> at IncomingMessage. (/opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:2705:16)
> at IncomingMessage.emit (events.js:327:22)
> at endReadableNT (_stream_readable.js:1221:12)
> at processTicksAndRejections (internal/process/task_queues.js:84:21)
> 2021-06-09 18:52:43.796  - error: swiss-weather-api.0 (15999) Cannot read property 'id' of undefined
> 2021-06-09 18:52:43.820  - info: swiss-weather-api.0 (15999) cleaned everything up...
> 2021-06-09 18:52:43.821  - info: swiss-weather-api.0 (15999) terminating
> 2021-06-09 18:52:43.824  - warn: swiss-weather-api.0 (15999) Terminated (UNCAUGHT_EXCEPTION): Without reason
> 2021-06-09 18:52:44.508  - error: host.ioBroker-RasPi instance system.adapter.swiss-weather-api.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
> 2021-06-09 18:52:44.511  - info: host.ioBroker-RasPi Restart adapter system.adapter.swiss-weather-api.0 because enabled
> 2021-06-09 18:52:44.512  - warn: host.ioBroker-RasPi Do not restart adapter system.adapter.swiss-weather-api.0 because restart loop detected
> 
>

**Comment by baerengraben** [comment]
done
