### ISSUE TITLE
Date/Time not recognised in 24h forecast 

### ISSUE THREAD

**Issue by thGirard** [baerengraben/iobroker.swiss-weather-api#8]
Der Adapter ist super! Vielen Dank!
Bei der 24h Vorhersage (3-stündlich) wird leider das Datum nicht erkannt. So weiss ich nicht, welche Uhrzeit welchen values entspricht.Das Feld 'date' hat den Wert 'invalid date'
In der Datei 'response24hForecast' beginnt es bei 01:00 des laufenden Tages und geht bis 22:00, wenn ich die API heute aufrufe, dann geht es von 02:00 bis 23:00.

mit freundlichen Grüssen   Thierry Girard

**Comment by baerengraben** [comment]
Hi Thierry
Vielen Dank für die Info. Da scheint die SRG etwas an der API verändert zu haben. Seit heute erhalte ich auch diesen Fehler. Ich werde Analyse und Korrektur asap umsetzen.
Viele Grüsse

**Comment by baerengraben** [comment]
Hi Thierry
Ich habe es mir mal genauer angeschaut. Mein erster Gedanke, wobei es sich um einen Fehler des APIs handelt, hat sich nicht bewahrheitet. Vielmehr habe ich den Fehler seither nicht mehr bekommen. Das Datum wird bei mir korrekt angezeigt:

![grafik](https://user-images.githubusercontent.com/9572444/81558099-65741680-938d-11ea-91dd-3bc0b3317ccc.png)

Kannst du mir bitte den Fehler nochmals genauer beschreiben?

**Comment by thGirard** [comment]
Vielen Dank für die Rückmeldung

Bei mir besteht der Fehler. Mein System läuft auf Englisch. Könnte das eine Ursache haben?
Interessanterweise ist das Datum bei ‚CurrentForecast.current_day.date‘ korrekt, während es bei ‚CurrentForecast.current_hour_date‘ eine Fehlermeldung gibt.

ich könnte auch problemlos ein „Stück“ Javacode im ioBroker testen.


Falls das was bringt, auf meinem System funktioniert (mit einem anderen Adapter):

stringToConvert = 'Tue May 12 2020 07:00:00 GMT+0200 (CEST)';
myDate = new Date(stringToConvert);

beste Grüsse
Thierry Girard

**Comment by baerengraben** [comment]
Hi Thierry

> In der Datei 'response24hForecast' beginnt es bei 01:00 des laufenden Tages und geht bis 22:00, wenn ich die API heute aufrufe, dann geht es von 02:00 bis 23:00.

Hier liefert SRF neu andere Werte, wie damals als ich den Adapter entwickelt habe. Aber das ist soweit kein Problem.

Ansonsten habe ich nochmals den Code überprüft. Ich sehe aktuell keine Fehler. Auch die Spracheinstellung sollte eigentlich kein Problem darstellen. Ich erstelle aktuell die Version 0.2.1 Kannst du bitte diese Version installieren und den loglevel auf "debug" stellen? Evtl. kommen wir dem Problem so auf die Spur.

Viele Grüsse
Ralph

**Comment by thGirard** [comment]
Hallo Ralph

vielen herzlichen Dank!
Ich habe es installiert (also nicht neu installiert, sondern update gemacht).
Bei den Objekten steht bei der Zeit ‚invalid date‘ (s. Screenshot).


hilft das log? Soll ich löschen und neu installieren?

beste Grüsse
Thierry


2020-07-23 11:00:00.306 - debug: swiss-weather-api.0 (18177) Redis Objects: Use Redis connection: 0.0.0.0:9001
2020-07-23 11:00:00.322 - debug: swiss-weather-api.0 (18177) Objects client ready ... initialize now
2020-07-23 11:00:00.323 - debug: swiss-weather-api.0 (18177) Objects create System PubSub Client
2020-07-23 11:00:00.324 - debug: swiss-weather-api.0 (18177) Objects create User PubSub Client
2020-07-23 11:00:00.324 - debug: swiss-weather-api.0 (18177) Objects client initialize lua scripts
2020-07-23 11:00:00.337 - debug: swiss-weather-api.0 (18177) Objects connected to redis: 0.0.0.0:9001
2020-07-23 11:00:00.340 - debug: swiss-weather-api.0 (18177) objectDB connected
2020-07-23 11:00:00.340 - debug: swiss-weather-api.0 (18177) Redis States: Use Redis connection: 0.0.0.0:9000
2020-07-23 11:00:00.355 - debug: swiss-weather-api.0 (18177) States create User PubSub Client
2020-07-23 11:00:00.356 - debug: swiss-weather-api.0 (18177) States create System PubSub Client
2020-07-23 11:00:00.385 - debug: swiss-weather-api.0 (18177) States connected to redis: 0.0.0.0:9000
2020-07-23 11:00:00.385 - debug: swiss-weather-api.0 (18177) statesDB connected
2020-07-23 11:00:01.301 - info: swiss-weather-api.0 (18177) starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.swiss-weather-api, node: v10.22.0, js-controller: 3.1.6
2020-07-23 11:00:01.310 - info: swiss-weather-api.0 (18177) Swiss-Weather-API: Start getWeatherInfos
2020-07-23 11:00:01.310 - debug: swiss-weather-api.0 (18177) App Name: ioBroker
2020-07-23 11:00:01.310 - debug: swiss-weather-api.0 (18177) Consumer Key: aFFwjaHFwFAvSX6mw2JG2ficiKGx6oKH
2020-07-23 11:00:01.310 - debug: swiss-weather-api.0 (18177) Consumer Secret: IXaFxqkBsgGqMEDo
2020-07-23 11:00:01.310 - debug: swiss-weather-api.0 (18177) Latitude 47.5490
2020-07-23 11:00:01.310 - debug: swiss-weather-api.0 (18177) Longitude: 7.5740
2020-07-23 11:00:01.310 - debug: swiss-weather-api.0 (18177) Define XML File:...
2020-07-23 11:00:01.311 - debug: swiss-weather-api.0 (18177) "aFFwjaHFwFAvSX6mw2JG2ficiKGx6oKH:IXaFxqkBsgGqMEDo" converted to Base64 is "YUZGd2phSEZ3RkF2U1g2bXcySkcyZmljaUtHeDZvS0g6SVhhRnhxa0JzZ0dxTUVEbw=="
2020-07-23 11:00:01.404 - debug: swiss-weather-api.0 (18177) Access_Token : 6tuXQawm3OhZcGczxqieKxHdTYj1
2020-07-23 11:00:02.370 - debug: swiss-weather-api.0 (18177) chunksConcat: 
{"sevendays":[{"date":"2020-07-23","values":[{"ttn":"15.6"},{"smbd":"10"},{"ttx":"28.2"}],"formatted_date":"23.07.2020"},{"date":"2020-07-24","values":[{"ttn":"16.8"},{"smbd":"3"},{"ttx":"25.8"}],"formatted_date":"24.07.2020"},{"date":"2020-07-25","values":[{"ttn":"15.5"},{"smbd":"3"},{"ttx":"28.1"}],"formatted_date":"25.07.2020"},{"date":"2020-07-26","values":[{"ttn":"17.5"},{"smbd":"3"},{"ttx":"25.3"}],"formatted_date":"26.07.2020"},{"date":"2020-07-27","values":[{"ttn":"16.3"},{"smbd":"3"},{"ttx":"26.4"}],"formatted_date":"27.07.2020"},{"date":"2020-07-28","values":[{"ttn":"15.4"},{"smbd":"10"},{"ttx":"28.6"}],"formatted_date":"28.07.2020"},{"date":"2020-07-29","values":[{"ttn":"17.6"},{"smbd":"3"},{"ttx":"27.2"}],"formatted_date":"29.07.2020"}],"info":{"id":4054,"name":{"de":"Basel"},"plz":4054},"type":"forecasts","units":{"dd3":{"name":"winddirection_10m_mean_3h","unit":"°"},"ddd":{"name":"winddirection_10m_mean_1d","unit":"°"},"ff3":{"name":"windspeed_10m_mean_3h","unit":"km/h"},"ffd":{"name":"windspeed_10m_mean_1d","unit":"km/h"},"fff":{"name":"windspeed_10m_mean_1h","unit":"km/h"},"ffx3":{"name":"windspeed_10m_max_3h","unit":"km/h"},"fxd":{"name":"windspeed_10m_max_1d","unit":"km/h"},"pr3":{"name":"probrain_3h","unit":"%"},"prd":{"name":"probrain_1d","unit":"%"},"rr3":{"name":"precipitation_1.5m_sum_3h","unit":"mm"},"rsd":{"name":"precipitation_1.5m_sum_1d","unit":"mm"},"smb3":{"name":"symbol","unit":"code"},"smbd":{"name":"symbol","unit":"code"},"ttn":{"name":"temperature_2m_min","unit":"°C"},"ttt":{"name":"temperature_2m_act","unit":"°C"},"ttx":{"name":"temperature_2m_max","unit":"°C"}}}
2020-07-23 11:00:02.370 - debug: swiss-weather-api.0 (18177) Week Forecast: {"sevendays":[{"date":"2020-07-23","values":[{"ttn":"15.6"},{"smbd":"10"},{"ttx":"28.2"}],"formatted_date":"23.07.2020"},{"date":"2020-07-24","values":[{"ttn":"16.8"},{"smbd":"3"},{"ttx":"25.8"}],"formatted_date":"24.07.2020"},{"date":"2020-07-25","values":[{"ttn":"15.5"},{"smbd":"3"},{"ttx":"28.1"}],"formatted_date":"25.07.2020"},{"date":"2020-07-26","values":[{"ttn":"17.5"},{"smbd":"3"},{"ttx":"25.3"}],"formatted_date":"26.07.2020"},{"date":"2020-07-27","values":[{"ttn":"16.3"},{"smbd":"3"},{"ttx":"26.4"}],"formatted_date":"27.07.2020"},{"date":"2020-07-28","values":[{"ttn":"15.4"},{"smbd":"10"},{"ttx":"28.6"}],"formatted_date":"28.07.2020"},{"date":"2020-07-29","values":[{"ttn":"17.6"},{"smbd":"3"},{"ttx":"27.2"}],"formatted_date":"29.07.2020"}],"info":{"id":4054,"name":{"de":"Basel"},"plz":4054},"type":"forecasts","units":{"dd3":{"name":"winddirection_10m_mean_3h","unit":"°"},"ddd":{"name":"winddirection_10m_mean_1d","unit":"°"},"ff3":{"name":"windspeed_10m_mean_3h","unit":"km/h"},"ffd":{"name":"windspeed_10m_mean_1d","unit":"km/h"},"fff":{"name":"windspeed_10m_mean_1h","unit":"km/h"},"ffx3":{"name":"windspeed_10m_max_3h","unit":"km/h"},"fxd":{"name":"windspeed_10m_max_1d","unit":"km/h"},"pr3":{"name":"probrain_3h","unit":"%"},"prd":{"name":"probrain_1d","unit":"%"},"rr3":{"name":"precipitation_1.5m_sum_3h","unit":"mm"},"rsd":{"name":"precipitation_1.5m_sum_1d","unit":"mm"},"smb3":{"name":"symbol","unit":"code"},"smbd":{"name":"symbol","unit":"code"},"ttn":{"name":"temperature_2m_min","unit":"°C"},"ttt":{"name":"temperature_2m_act","unit":"°C"},"ttx":{"name":"temperature_2m_max","unit":"°C"}}}
2020-07-23 11:00:02.371 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for weekforecast.day0
2020-07-23 11:00:02.371 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy-high
2020-07-23 11:00:02.372 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for weekforecast.day1
2020-07-23 11:00:02.372 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy
2020-07-23 11:00:02.373 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for weekforecast.day2
2020-07-23 11:00:02.373 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy
2020-07-23 11:00:02.373 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for weekforecast.day3
2020-07-23 11:00:02.373 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy
2020-07-23 11:00:02.374 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for weekforecast.day4
2020-07-23 11:00:02.374 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy
2020-07-23 11:00:02.375 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for weekforecast.day5
2020-07-23 11:00:02.375 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy-high
2020-07-23 11:00:02.375 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for weekforecast.day6
2020-07-23 11:00:02.375 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy
2020-07-23 11:00:02.378 - debug: swiss-weather-api.0 (18177) Weather-Icon Name day0: wi-day-cloudy-high
2020-07-23 11:00:02.378 - debug: swiss-weather-api.0 (18177) Weather-Icon Name day1: wi-day-cloudy
2020-07-23 11:00:02.379 - debug: swiss-weather-api.0 (18177) Weather-Icon Name day2: wi-day-cloudy
2020-07-23 11:00:02.380 - debug: swiss-weather-api.0 (18177) Weather-Icon Name day3: wi-day-cloudy
2020-07-23 11:00:02.381 - debug: swiss-weather-api.0 (18177) Weather-Icon Name day4: wi-day-cloudy
2020-07-23 11:00:02.382 - debug: swiss-weather-api.0 (18177) Weather-Icon Name day5: wi-day-cloudy-high
2020-07-23 11:00:02.383 - debug: swiss-weather-api.0 (18177) Weather-Icon Name day6: wi-day-cloudy
2020-07-23 11:00:02.407 - debug: swiss-weather-api.0 (18177) Hour Forecast: {"formatted_date":"23.07.2020","date":"2020-07-23","nexthour":[{"date":"2020-07-23T11:00:00+0200","values":[{"smb3":"10"},{"ttt":"22.1"},{"fff":"6"},{"ffx3":"15"},{"ddd":"281"},{"rr3":"0.0"},{"pr3":"1"}]}],"info":{"id":4054,"name":{"de":"Basel"},"plz":4054},"type":"forecasts","units":{"dd3":{"name":"winddirection_10m_mean_3h","unit":"°"},"ddd":{"name":"winddirection_10m_mean_1d","unit":"°"},"ff3":{"name":"windspeed_10m_mean_3h","unit":"km/h"},"ffd":{"name":"windspeed_10m_mean_1d","unit":"km/h"},"fff":{"name":"windspeed_10m_mean_1h","unit":"km/h"},"ffx3":{"name":"windspeed_10m_max_3h","unit":"km/h"},"fxd":{"name":"windspeed_10m_max_1d","unit":"km/h"},"pr3":{"name":"probrain_3h","unit":"%"},"prd":{"name":"probrain_1d","unit":"%"},"rr3":{"name":"precipitation_1.5m_sum_3h","unit":"mm"},"rsd":{"name":"precipitation_1.5m_sum_1d","unit":"mm"},"smb3":{"name":"symbol","unit":"code"},"smbd":{"name":"symbol","unit":"code"},"ttn":{"name":"temperature_2m_min","unit":"°C"},"ttt":{"name":"temperature_2m_act","unit":"°C"},"ttx":{"name":"temperature_2m_max","unit":"°C"}}}
2020-07-23 11:00:02.407 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for hourforecast.nexthour
2020-07-23 11:00:02.408 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy-high
2020-07-23 11:00:02.410 - debug: swiss-weather-api.0 (18177) Weather-Icon Name nexthour: wi-day-cloudy-high
2020-07-23 11:00:02.422 - debug: swiss-weather-api.0 (18177) Current Forecast: {"formatted_date":"23.07.2020","current_day":{"date":"2020-07-23","values":[{"ttn":"15.6"},{"smbd":"10"},{"ttx":"28.2"}]},"current_hour":[{"date":"2020-07-23T11:00:00+0200","values":[{"smb3":"10"},{"ttt":"22.1"},{"fff":"6"},{"ffx3":"15"},{"ddd":"281"},{"rr3":"0.0"},{"pr3":"1"}]}],"info":{"id":4054,"name":{"de":"Basel"},"plz":4054},"type":"forecasts","units":{"dd3":{"name":"winddirection_10m_mean_3h","unit":"°"},"ddd":{"name":"winddirection_10m_mean_1d","unit":"°"},"ff3":{"name":"windspeed_10m_mean_3h","unit":"km/h"},"ffd":{"name":"windspeed_10m_mean_1d","unit":"km/h"},"fff":{"name":"windspeed_10m_mean_1h","unit":"km/h"},"ffx3":{"name":"windspeed_10m_max_3h","unit":"km/h"},"fxd":{"name":"windspeed_10m_max_1d","unit":"km/h"},"pr3":{"name":"probrain_3h","unit":"%"},"prd":{"name":"probrain_1d","unit":"%"},"rr3":{"name":"precipitation_1.5m_sum_3h","unit":"mm"},"rsd":{"name":"precipitation_1.5m_sum_1d","unit":"mm"},"smb3":{"name":"symbol","unit":"code"},"smbd":{"name":"symbol","unit":"code"},"ttn":{"name":"temperature_2m_min","unit":"°C"},"ttt":{"name":"temperature_2m_act","unit":"°C"},"ttx":{"name":"temperature_2m_max","unit":"°C"}}}
2020-07-23 11:00:02.423 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for current day
2020-07-23 11:00:02.423 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy-high
2020-07-23 11:00:02.423 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for current hour
2020-07-23 11:00:02.424 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy-high
2020-07-23 11:00:02.426 - debug: swiss-weather-api.0 (18177) Weather-Icon Name current_day: wi-day-cloudy-high
2020-07-23 11:00:02.427 - debug: swiss-weather-api.0 (18177) Weather-Icon Name current_hour: wi-day-cloudy-high
2020-07-23 11:00:02.536 - debug: swiss-weather-api.0 (18177) chunksConcat: 
{"formatted_date":"23.07.2020","date":"2020-07-23","twentyfourhours":[{"date":"2020-07-23T02:00:00+0200","values":[{"smb3":"-1"},{"ttt":"17.6"},{"fff":"6"},{"ffx3":""},{"ddd":"218"}]},{"date":"2020-07-23T05:00:00+0200","values":[{"smb3":"-1"},{"ttt":"16.4"},{"fff":"4"},{"ffx3":""},{"ddd":"214"}]},{"date":"2020-07-23T08:00:00+0200","values":[{"smb3":"-10"},{"ttt":"16.7"},{"fff":"4"},{"ffx3":"11"},{"ddd":"230"},{"rr3":"0.0"},{"pr3":"1"}]},{"date":"2020-07-23T11:00:00+0200","values":[{"smb3":"10"},{"ttt":"22.1"},{"fff":"6"},{"ffx3":"15"},{"ddd":"281"},{"rr3":"0.0"},{"pr3":"1"}]},{"date":"2020-07-23T14:00:00+0200","values":[{"smb3":"10"},{"ttt":"25.9"},{"fff":"6"},{"ffx3":"20"},{"ddd":"292"},{"rr3":"0.0"},{"pr3":"1"}]},{"date":"2020-07-23T17:00:00+0200","values":[{"smb3":"10"},{"ttt":"27.5"},{"fff":"7"},{"ffx3":"22"},{"ddd":"289"},{"rr3":"0.0"},{"pr3":"1"}]},{"date":"2020-07-23T20:00:00+0200","values":[{"smb3":"10"},{"ttt":"26.5"},{"fff":"6"},{"ffx3":"22"},{"ddd":"295"},{"rr3":"0.0"},{"pr3":"1"}]},{"date":"2020-07-23T23:00:00+0200","values":[{"smb3":"-3"},{"ttt":"21.5"},{"fff":"6"},{"ffx3":"17"},{"ddd":"231"},{"rr3":"0.0"},{"pr3":"1"}]}],"info":{"id":4054,"name":{"de":"Basel"},"plz":4054},"type":"forecasts","units":{"dd3":{"name":"winddirection_10m_mean_3h","unit":"°"},"ddd":{"name":"winddirection_10m_mean_1d","unit":"°"},"ff3":{"name":"windspeed_10m_mean_3h","unit":"km/h"},"ffd":{"name":"windspeed_10m_mean_1d","unit":"km/h"},"fff":{"name":"windspeed_10m_mean_1h","unit":"km/h"},"ffx3":{"name":"windspeed_10m_max_3h","unit":"km/h"},"fxd":{"name":"windspeed_10m_max_1d","unit":"km/h"},"pr3":{"name":"probrain_3h","unit":"%"},"prd":{"name":"probrain_1d","unit":"%"},"rr3":{"name":"precipitation_1.5m_sum_3h","unit":"mm"},"rsd":{"name":"precipitation_1.5m_sum_1d","unit":"mm"},"smb3":{"name":"symbol","unit":"code"},"smbd":{"name":"symbol","unit":"code"},"ttn":{"name":"temperature_2m_min","unit":"°C"},"ttt":{"name":"temperature_2m_act","unit":"°C"},"ttx":{"name":"temperature_2m_max","unit":"°C"}}}
2020-07-23 11:00:02.537 - debug: swiss-weather-api.0 (18177) 24h Forecast: {"formatted_date":"23.07.2020","date":"2020-07-23","twentyfourhours":[{"date":"2020-07-23T02:00:00+0200","values":[{"smb3":"-1"},{"ttt":"17.6"},{"fff":"6"},{"ffx3":""},{"ddd":"218"}]},{"date":"2020-07-23T05:00:00+0200","values":[{"smb3":"-1"},{"ttt":"16.4"},{"fff":"4"},{"ffx3":""},{"ddd":"214"}]},{"date":"2020-07-23T08:00:00+0200","values":[{"smb3":"-10"},{"ttt":"16.7"},{"fff":"4"},{"ffx3":"11"},{"ddd":"230"},{"rr3":"0.0"},{"pr3":"1"}]},{"date":"2020-07-23T11:00:00+0200","values":[{"smb3":"10"},{"ttt":"22.1"},{"fff":"6"},{"ffx3":"15"},{"ddd":"281"},{"rr3":"0.0"},{"pr3":"1"}]},{"date":"2020-07-23T14:00:00+0200","values":[{"smb3":"10"},{"ttt":"25.9"},{"fff":"6"},{"ffx3":"20"},{"ddd":"292"},{"rr3":"0.0"},{"pr3":"1"}]},{"date":"2020-07-23T17:00:00+0200","values":[{"smb3":"10"},{"ttt":"27.5"},{"fff":"7"},{"ffx3":"22"},{"ddd":"289"},{"rr3":"0.0"},{"pr3":"1"}]},{"date":"2020-07-23T20:00:00+0200","values":[{"smb3":"10"},{"ttt":"26.5"},{"fff":"6"},{"ffx3":"22"},{"ddd":"295"},{"rr3":"0.0"},{"pr3":"1"}]},{"date":"2020-07-23T23:00:00+0200","values":[{"smb3":"-3"},{"ttt":"21.5"},{"fff":"6"},{"ffx3":"17"},{"ddd":"231"},{"rr3":"0.0"},{"pr3":"1"}]}],"info":{"id":4054,"name":{"de":"Basel"},"plz":4054},"type":"forecasts","units":{"dd3":{"name":"winddirection_10m_mean_3h","unit":"°"},"ddd":{"name":"winddirection_10m_mean_1d","unit":"°"},"ff3":{"name":"windspeed_10m_mean_3h","unit":"km/h"},"ffd":{"name":"windspeed_10m_mean_1d","unit":"km/h"},"fff":{"name":"windspeed_10m_mean_1h","unit":"km/h"},"ffx3":{"name":"windspeed_10m_max_3h","unit":"km/h"},"fxd":{"name":"windspeed_10m_max_1d","unit":"km/h"},"pr3":{"name":"probrain_3h","unit":"%"},"prd":{"name":"probrain_1d","unit":"%"},"rr3":{"name":"precipitation_1.5m_sum_3h","unit":"mm"},"rsd":{"name":"precipitation_1.5m_sum_1d","unit":"mm"},"smb3":{"name":"symbol","unit":"code"},"smbd":{"name":"symbol","unit":"code"},"ttn":{"name":"temperature_2m_min","unit":"°C"},"ttt":{"name":"temperature_2m_act","unit":"°C"},"ttx":{"name":"temperature_2m_max","unit":"°C"}}}
2020-07-23 11:00:02.537 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for 24h forecast.hour0: -1
2020-07-23 11:00:02.537 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-night-clear
2020-07-23 11:00:02.538 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for 24h forecast.hour1: -1
2020-07-23 11:00:02.538 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-night-clear
2020-07-23 11:00:02.539 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for 24h forecast.hour2: -10
2020-07-23 11:00:02.539 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-night-alt-partly-cloudy
2020-07-23 11:00:02.540 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for 24h forecast.hour3: 10
2020-07-23 11:00:02.540 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy-high
2020-07-23 11:00:02.541 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for 24h forecast.hour4: 10
2020-07-23 11:00:02.541 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy-high
2020-07-23 11:00:02.541 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for 24h forecast.hour5: 10
2020-07-23 11:00:02.542 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy-high
2020-07-23 11:00:02.542 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for 24h forecast.hour6: 10
2020-07-23 11:00:02.543 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-day-cloudy-high
2020-07-23 11:00:02.543 - debug: swiss-weather-api.0 (18177) get icon-url by xpath for 24h forecast.hour7: -3
2020-07-23 11:00:02.544 - debug: swiss-weather-api.0 (18177) Weather-Icon Name: wi-night-alt-cloudy
2020-07-23 11:00:02.545 - debug: swiss-weather-api.0 (18177) Weather-Icon Name hour0: wi-night-clear
2020-07-23 11:00:02.547 - debug: swiss-weather-api.0 (18177) Weather-Icon Name hour1: wi-night-clear
2020-07-23 11:00:02.548 - debug: swiss-weather-api.0 (18177) Weather-Icon Name hour2: wi-night-alt-partly-cloudy
2020-07-23 11:00:02.549 - debug: swiss-weather-api.0 (18177) Weather-Icon Name hour3: wi-day-cloudy-high
2020-07-23 11:00:02.551 - debug: swiss-weather-api.0 (18177) Weather-Icon Name hour4: wi-day-cloudy-high
2020-07-23 11:00:02.552 - debug: swiss-weather-api.0 (18177) Weather-Icon Name hour5: wi-day-cloudy-high
2020-07-23 11:00:02.552 - debug: swiss-weather-api.0 (18177) Weather-Icon Name hour5: wi-day-cloudy-high
2020-07-23 11:00:02.553 - debug: swiss-weather-api.0 (18177) Weather-Icon Name hour6: wi-day-cloudy-high
2020-07-23 11:00:02.555 - debug: swiss-weather-api.0 (18177) Weather-Icon Name hour7: wi-night-alt-cloudy
2020-07-23 11:00:02.556 - error: swiss-weather-api.0 (18177) uncaught exception: Cannot read property 'rr3' of undefined
2020-07-23 11:00:02.557 - error: swiss-weather-api.0 (18177) TypeError: Cannot read property 'rr3' of undefined
at /opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1826:48
at adapterObjects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3216:55)
at (anonymous function).get (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703)
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
at process._tickCallback (internal/process/next_tick.js:68:7)
2020-07-23 11:00:02.558 - debug: swiss-weather-api.0 (18177) cleaned everything up...
2020-07-23 11:00:02.558 - error: swiss-weather-api.0 (18177) uncaught exception: Cannot read property 'pr3' of undefined
2020-07-23 11:00:02.558 - error: swiss-weather-api.0 (18177) TypeError: Cannot read property 'pr3' of undefined
at /opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:1841:48
at adapterObjects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3216:55)
at (anonymous function).get (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703)
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
at process._tickCallback (internal/process/next_tick.js:68:7)
2020-07-23 11:00:02.559 - error: swiss-weather-api.0 (18177) uncaught exception: Cannot read property 'rr3' of undefined
2020-07-23 11:00:02.559 - error: swiss-weather-api.0 (18177) TypeError: Cannot read property 'rr3' of undefined
at /opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:2003:48
at adapterObjects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3216:55)
at (anonymous function).get (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703)
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
at process._tickCallback (internal/process/next_tick.js:68:7)
2020-07-23 11:00:02.559 - error: swiss-weather-api.0 (18177) uncaught exception: Cannot read property 'pr3' of undefined
2020-07-23 11:00:02.559 - error: swiss-weather-api.0 (18177) TypeError: Cannot read property 'pr3' of undefined
at /opt/iobroker/node_modules/iobroker.swiss-weather-api/main.js:2018:48
at adapterObjects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3216:55)
at (anonymous function).get (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93703)
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
at process._tickCallback (internal/process/next_tick.js:68:7)
2020-07-23 11:00:02.594 - info: swiss-weather-api.0 (18177) terminating
2020-07-23 11:00:02.595 - info: swiss-weather-api.0 (18177) Terminated (NO_ERROR): Without reason

**Comment by baerengraben** [comment]
Hi Thierry
Danke fürs Log. Das hat schon mal geholfen:

> {"formatted_date":"23.07.2020","date":"2020-07-23","twentyfourhours":[{"date":"**2020-07-23T02:00:00+0200**","values":[{"smb3":"-1"},{"ttt":"17.6"},{"fff":"6"},{"ffx3":""},{"ddd":"218"}]},{"date":"2020-07-23T05:00:00+0200","values":[{"smb3":"-1"},{"ttt":"16.4"},{"fff":"4"},{"ffx3":""},{"ddd":"214"}]},{"date":"2020-07-23T08:00:00+0200","values":[{"smb3":"-10"},{"ttt":"16.7"},{"fff":"4"},{"ffx3":"11"},{"ddd":"230"},{"rr3":"0.0"},{"pr3":"1"}]},{"date":"2020-07-23T11:00:00+0200","values":[{"smb3":"10"},{"ttt":"22.1"},{"fff":"6"},{"ffx3":"15"},{"ddd":"281"},{"rr3":"0.0"},{"pr3":"1"}]},{"date":"2020-07-23T14:00:00+0200","values":[{"smb3":"10"},{"ttt":"25.9"},{"fff":"6"},{"ffx3":"20"},{"ddd":"292"},{"rr3":"0.0"},{"pr3":"1"}]}, 

Hier sieht man, dass das Datum schon mal korrekt vom API geliefert wird. Da muss irgendwo beim Abfüllen in die Objektliste was nicht korrekt ablaufen. Kannst du bitte mal einen Print-Screen vom ioBroker posten? Am besten die gleiche Sicht, wie hier:
![Bildschirmfoto vom 2020-07-23 16-37-09](https://user-images.githubusercontent.com/9572444/88299616-d8d9c300-cd02-11ea-9877-9263624d83fc.png)

**Comment by thGirard** [comment]
klar, gerne!


liebe Grüsse Thierry

**Comment by baerengraben** [comment]
Hi Thierry
Dein Print-Screen wird bei mir nicht angezeigt. Upload vergessen? ;)

**Comment by baerengraben** [comment]
closed due to inactivity
